!ymlDefine.YmlDefine$StorageRegistrarConfig
DBCredentialConfigFilePath: config/DBLoginCredential.yml
backUpAfterMilli: 2000
currentStorageCount: 0
#IP address of the host OR localhost
hostName: localhost
port: 4567
version: ISRA
