!ymlDefine.YmlDefine$ConsoleConfig
DBCredentialConfigFilePath: 'config/DBLoginCredential.yml'
extHardwareConfigFilePath: 'config/externalIOConfig.yml'
WMRequestListenerPort: 9988
defaultTargetNodeId: testNode001
opencvJarPath: ''
