!ymlDefine.YmlDefine$ExternalIOConfig
#Enter external interface devices path and URL. Path is physical location, URL is network location eg Streams.
#'' empty string means unused.
visualInURL: ''
audioInURL: ''
audioOutPath: ''
rpiURL: ''
motor1InURL: ''
motor1OutPath: ''
motor2InURL: ''
motor2OutPath: ''
motor3InURL: ''
motor3OutPath: ''
motor4InURL: ''
motor4OutPath: ''
